# Create a Netatmo developer account and fill in here the details:
netatmo:
  client_id: NETATMO_CLIENT_ID
  client_secret: NETATMO_CLIENT_SECRET
  refresh_token: NETATMO_REFRESH_TOKEN
  access_token: NETATMO_ACCESS_TOKEN
  token_valid_until: 2024-06-22T13:39:21.200055+02:00

# Fill in here influx details
influx:
  url: http://localhost:8086
  token: my-token
  bucket: my-bucket
  org: my-org
